apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ns241019
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30019
  type: NodePort

